const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export interface EventInput {
  title: string;
  date: string;
  speaker: string;
  registration_link: string;
  audience: string;
  description: string;
}

export interface SocialPostOutput {
  caption: string;
  hashtags: string[];
  suggested_image_prompt: string;
  cta: string;
}

/** One social post option within a 3-variant generation batch (see
 * GeneratedContentResponse.social_post_variants). structure_variant is
 * the raw key ("standard"/"listicle"/"quote_style", or a platform key) —
 * pass it back as-is when persisting via selectSocialVariant(). */
export interface SocialPostVariant {
  structure_variant: string;
  structure_label: string;
  post: SocialPostOutput;
}

export interface HashtagsOutput {
  primary_hashtags: string[];
  topic_hashtags: string[];
  rationale: string;
}

/** One hashtag-set option, paired 1:1 by array index with the
 * SocialPostVariant generated alongside it — see
 * GeneratedContentResponse.hashtags_variants. */
export interface HashtagsVariant {
  hashtags: HashtagsOutput;
}

export interface NewsletterOutput {
  subject_line: string;
  preview_text: string;
  body: string;
  body_plain_text: string;
  cta_text: string;
  cta_link: string;
}

export interface FlyerOutput {
  headline: string;
  subheadline: string;
  body: string;
  cta: string;
  footer_details: string;
}

export interface CalendarPostEntry {
  day_label: string;
  platform: string;
  post_idea: string;
  hashtags: string[];
  cta: string;
}

export interface ContentCalendarOutput {
  weeks: number;
  entries: CalendarPostEntry[];
}

export interface GeneratedContentResponse {
  /** Pass back to selectSocialVariant() once staff picks a social post
   * option — social_post/hashtags aren't persisted until that call. */
  event_id: number;
  /** Parallel arrays — same length, same index = generated together. */
  social_post_variants: SocialPostVariant[];
  hashtags_variants: HashtagsVariant[];
  newsletter: NewsletterOutput;
  flyer: FlyerOutput;
  calendar: ContentCalendarOutput;
}

export interface ContentItemResponse {
  id: number;
  event_id: number | null;
  key_maker_id: number | null;
  content_type: string;
  block_type: string | null;
  platform: string | null;
  status: string;
  structure_variant: string | null;
  body: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface EventWithContentResponse {
  id: number;
  title: string;
  date: string;
  speaker: string;
  registration_link: string;
  audience: string;
  description: string;
  created_at: string;
  updated_at: string;
  content_items: ContentItemResponse[];
}

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_URL}${path}`, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });

  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`API request failed (${res.status}): ${detail}`);
  }

  return res.json() as Promise<T>;
}

/** Platform-specific social post structure variants (see
 * SOCIAL_POST_PLATFORM_VARIANTS in prompts.py) — a deliberate staff
 * choice, distinct from tone-variant rotation (standard/listicle/
 * quote_style), which stays random ("generate_new") unless a platform is
 * explicitly picked here. instagram/linkedin/facebook are grounded in
 * real WVF post screenshots; x/tiktok use generic platform conventions
 * only — no real WVF X/TikTok samples have been reviewed yet. */
export const SOCIAL_POST_PLATFORMS = ["instagram", "linkedin", "facebook", "x", "tiktok"] as const;
export type SocialPostPlatform = (typeof SOCIAL_POST_PLATFORMS)[number];

export interface GenerateOptions {
  /** When set, the newsletter is generated by adapting the selected real
   * Keymakers recruitment reference message instead of normal event
   * promotion — see GET /api/keymakers-stages for valid keys. */
  keymakersStageKey?: string;
  /** When set, the social post is generated for this specific platform's
   * real observed structure (see SOCIAL_POST_PLATFORMS) instead of the
   * default random tone-variant rotation. */
  socialPostPlatform?: SocialPostPlatform;
}

export function generateContent(
  event: EventInput,
  options?: GenerateOptions
): Promise<GeneratedContentResponse> {
  return request<GeneratedContentResponse>("/api/generate", {
    method: "POST",
    body: JSON.stringify({
      ...event,
      ...(options?.keymakersStageKey
        ? { keymakers_stage_key: options.keymakersStageKey }
        : {}),
      ...(options?.socialPostPlatform
        ? { social_post_platform: options.socialPostPlatform }
        : {}),
    }),
  });
}

/** Persists the social post + hashtags option staff picked from the
 * 3-variant batch generateContent() returned. Must be called exactly
 * once per event, after generateContent() — social_post/hashtags
 * ContentItems don't exist in the database until this runs. Returns the
 * two newly-created ContentItemResponse rows (social post, then
 * hashtags). */
export function selectSocialVariant(
  eventId: number,
  socialPostVariant: SocialPostVariant,
  hashtags: HashtagsOutput
): Promise<ContentItemResponse[]> {
  return request<ContentItemResponse[]>("/api/content/select-social-variant", {
    method: "POST",
    body: JSON.stringify({
      event_id: eventId,
      social_post_variant: socialPostVariant,
      hashtags,
    }),
  });
}

export function listEvents(): Promise<EventWithContentResponse[]> {
  return request<EventWithContentResponse[]>("/api/events");
}

export function listKeymakersStages(): Promise<Record<string, string>> {
  return request<Record<string, string>>("/api/keymakers-stages");
}

/** One Keymakers stage's full real reference copy (label, audience,
 * subject line options, body) — the actual WVF campaign message text,
 * for instant display without an AI generation call. */
export interface KeymakersStageDetail {
  label: string;
  audience: string;
  stage: string;
  send_day: number;
  subject_options: string[] | null;
  body: string;
}

export function getKeymakersStageDetail(stageKey: string): Promise<KeymakersStageDetail> {
  return request<KeymakersStageDetail>(`/api/keymakers-stages/${encodeURIComponent(stageKey)}`);
}

export function listInstagramTemplates(): Promise<Record<string, string>> {
  return request<Record<string, string>>("/api/instagram-templates");
}

/** One real, published WVF Instagram post's full caption and hashtags —
 * for instant display/editing without an AI generation call. */
export interface InstagramTemplateDetail {
  label: string;
  category: string;
  caption: string;
  hashtags: string[];
}

export function getInstagramTemplateDetail(templateKey: string): Promise<InstagramTemplateDetail> {
  return request<InstagramTemplateDetail>(`/api/instagram-templates/${encodeURIComponent(templateKey)}`);
}
