const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export interface EventInput {
  title: string;
  date: string;
  speaker: string;
  registration_link: string;
  audience: string;
  description: string;
}

export interface SocialPostOutput {
  caption: string;
  hashtags: string[];
  suggested_image_prompt: string;
  cta: string;
}

export interface HashtagsOutput {
  primary_hashtags: string[];
  topic_hashtags: string[];
  rationale: string;
}

export interface NewsletterOutput {
  subject_line: string;
  preview_text: string;
  body: string;
  body_plain_text: string;
  cta_text: string;
  cta_link: string;
}

export interface FlyerOutput {
  headline: string;
  subheadline: string;
  body: string;
  cta: string;
  footer_details: string;
}

export interface CalendarPostEntry {
  day_label: string;
  platform: string;
  post_idea: string;
  hashtags: string[];
  cta: string;
}

export interface ContentCalendarOutput {
  weeks: number;
  entries: CalendarPostEntry[];
}

export interface GeneratedContentResponse {
  social_post: SocialPostOutput;
  hashtags: HashtagsOutput;
  newsletter: NewsletterOutput;
  flyer: FlyerOutput;
  calendar: ContentCalendarOutput;
}

export interface ContentItemResponse {
  id: number;
  event_id: number | null;
  key_maker_id: number | null;
  content_type: string;
  block_type: string | null;
  platform: string | null;
  status: string;
  structure_variant: string | null;
  body: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface EventWithContentResponse {
  id: number;
  title: string;
  date: string;
  speaker: string;
  registration_link: string;
  audience: string;
  description: string;
  created_at: string;
  updated_at: string;
  content_items: ContentItemResponse[];
}

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_URL}${path}`, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });

  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`API request failed (${res.status}): ${detail}`);
  }

  return res.json() as Promise<T>;
}

/** Platform-specific social post structure variants (see
 * SOCIAL_POST_PLATFORM_VARIANTS in prompts.py) — a deliberate staff
 * choice, distinct from tone-variant rotation (standard/listicle/
 * quote_style), which stays random ("generate_new") unless a platform is
 * explicitly picked here. */
export const SOCIAL_POST_PLATFORMS = ["instagram", "linkedin", "facebook"] as const;
export type SocialPostPlatform = (typeof SOCIAL_POST_PLATFORMS)[number];

export interface GenerateOptions {
  /** When set, the newsletter is generated by adapting the selected real
   * Keymakers recruitment reference message instead of normal event
   * promotion — see GET /api/keymakers-stages for valid keys. */
  keymakersStageKey?: string;
  /** When set, the social post is generated for this specific platform's
   * real observed structure (see SOCIAL_POST_PLATFORMS) instead of the
   * default random tone-variant rotation. */
  socialPostPlatform?: SocialPostPlatform;
}

export function generateContent(
  event: EventInput,
  options?: GenerateOptions
): Promise<GeneratedContentResponse> {
  return request<GeneratedContentResponse>("/api/generate", {
    method: "POST",
    body: JSON.stringify({
      ...event,
      ...(options?.keymakersStageKey
        ? { keymakers_stage_key: options.keymakersStageKey }
        : {}),
      ...(options?.socialPostPlatform
        ? { social_post_variant: options.socialPostPlatform }
        : {}),
    }),
  });
}

export function listEvents(): Promise<EventWithContentResponse[]> {
  return request<EventWithContentResponse[]>("/api/events");
}

export function listKeymakersStages(): Promise<Record<string, string>> {
  return request<Record<string, string>>("/api/keymakers-stages");
}
